version: 2.1

parameters:
  deploy-everything:
    type: boolean
    default: false
  deploy-hello-api:
    type: boolean
    default: false

jobs:
  deploy-everything:
    machine: true
    steps:
      - checkout
      - run:
          name: Deploy Everything
          command: |
            echo "deploy everything" 


  deploy-hello-api:
    machine: true
    steps:
      - checkout
      - run:
          name: Deploy Hello Api
          command: |
            echo "deploy hello api" 

workflows:
  deploy-everything:
    when: << pipeline.parameters.deploy-everything >>
    jobs:
      - deploy-whole

  deploy-hello-api:
    when: << pipeline.parameters.deploy-hello-api >>
    jobs:
      - deploy-hello-api
